#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/env.sh"

echo "================================================================================"
echo " Vertex AI Agent Runtime & SGP Enforcement Test Guide"
echo "================================================================================"
echo "1. Go to Google Cloud Console: Vertex AI > Reasoning Engines (or Agent Engine)"
echo "2. Select 'conversational-banking' and click the 'Playground' tab."
echo ""
echo "Multi-Turn Test Flow:"
echo "--------------------------------------------------------------------------------"
echo "[Turn 1 - Identify Customer]"
echo "Input:   I am customer CUST005"
echo "Expect:  Agent calls get_account, greets Alice Smith, shows balance ($10,000.00)."
echo ""
echo "[Turn 2 - Test Allowed Transaction (< $1,000 USD)]"
echo "Input:   transfer 50 to 555-0001"
echo "Expect:  SGP Verdict: ALLOW. Transfer succeeds, balance debited to $9,950.00."
echo ""
echo "[Turn 3 - Test Blocked Transaction (> $1,000 USD)]"
echo "Input:   transfer 2000 to 555-0002"
echo "Followup: y (if asked to confirm)"
echo "Expect:  SGP Verdict: DENY."
echo "         Agent reports refusal due to policy: transfer exceeding USD 1000 limit."
echo "--------------------------------------------------------------------------------"
echo ""
echo "To inspect audit logs in Cloud Logging:"
echo "gcloud logging read 'logName=\"projects/${PROJECT_ID}/logs/semantic-governance-policy\"' --limit=5 --format=json"
echo "================================================================================"
